import { SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["post"]["getAll"][number];

export function PostView(props: PostWithUser) {
	const { post, author } = props;

	const authorSaid = author?.username ? <div className="flex mb-1"><span className="text-gray-400 mr-2 font-bold">@{author.username}</span> · {dayjs(post.createdAt).fromNow()}</div> : '';

	return (
		<div key={post.id} data-author={author?.id} className="w-full rounded-xl bg-purple-500/10 p-4 text-white">
			{authorSaid}
			<span className="ml-4">{post.content}</span>
		</div>
	);

};

export function CreatePostWizard() {
	const user = useUser();

	if (user && user.isSignedIn) {
		return (
			<div className="flex w-full rounded-xl bg-white/10 p-4 text-white">
				<input placeholder="Enter your thoughts" className="w-full bg-transparent outline-none"/>
			</div>
		)
	}
};

export default function Home() {
	const { data } = api.post.getAll.useQuery();
	const user = useUser();

	return (
			<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">

					{!!user.isSignedIn && <div className="self-end rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"><SignOutButton /></div>}

					<h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
						Chirp
					</h1>
					<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
						<Link
							className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
							href="https://create.t3.gg/en/usage/first-steps"
							target="_blank"
							>
							<h3 className="text-2xl font-bold">First Steps →</h3>
							<div className="text-lg">
								Just the basics - Everything you need to know to set up your
								database and authentication.
							</div>
						</Link>
						<Link
							className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
							href="https://create.t3.gg/en/introduction"
							target="_blank"
							>
							<h3 className="text-2xl font-bold">Documentation →</h3>
							<div className="text-lg">
								Learn more about Create T3 App, the libraries it uses, and how
								to deploy it.
							</div>
						</Link>
					</div>
					<CreatePostWizard/>
					{data?.map((fullPost) => (
						<PostView {...fullPost} key={fullPost.post.id} />
					))}
				</div>
			</main>
			</>
	);
}
